services:
  app:
    build:
      context: ./aglink
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./aglink:/app
      - /app/node_modules
      - ~/.gitconfig:/root/.gitconfig
    container_name: aglink-app
    env_file: ./aglink/.env.local
# commandの指定がない場合、Dockerfileで指定
