# This is the name of the workflow, which will be displayed on GitHub's "Actions" tab.
name: Next.js CI

# This section defines when the workflow should be triggered.
# In this case, it runs whenever a pull request is created or updated.
on:
  pull_request:
    branches: ["main"] # It targets pull requests aimed at the 'main' branch.

# This section defines the jobs to be executed.
jobs:
  # 'check-and-build' is the unique ID for this job.
  check-and-build:
    # This specifies the type of machine the job will run on. 'ubuntu-latest' is a standard choice.
    runs-on: ubuntu-latest

    # 'steps' are the sequence of tasks that will be executed in this job.
    steps:
      # Step 1: Check out the repository's code
      # This allows the workflow to access your source code.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Node.js environment
      # This installs a specific version of Node.js for the workflow to use.
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # It's important to match this with your team's development environment version.
          node-version: "22"
          cache: "npm" # Enable caching for npm dependencies to speed up future runs.

      # Step 3: Install project dependencies
      # 'npm ci' is recommended for CI environments as it provides faster and more reliable installs.
      - name: Install dependencies
        run: npm ci

      # Step 4: Run the linter to check code quality
      # This command should be defined in your 'package.json' scripts.
      - name: Run linter
        run: npm run lint

      # Step 5: Run tests (if you have them)
      # This command should also be defined in your 'package.json'.
      # If you don't have tests yet, you can comment out or remove this step for now.
      - name: Run tests
        run: npm run test

      # Step 6: Run the build process to ensure the application builds successfully
      # This is a critical check to catch build errors before merging.
      - name: Build project
        run: npm run build
